tel: '+16132565225'
telDisplay: (613) 256-1234
email: info@thehubalmonte.com
hubContact:
  addressLine1: 14 Industrial Dr
  addressLine2: 'Almonte, ON K0A 1A0'
  mapLink: 'https://goo.gl/maps/2viaCeAw5n32'
  tel: '+16132565225'
  telDisplay: (613) 256-5225
reboundContact:
  addressLine1: 14 Industrial Dr
  addressLine2: 'Almonte, ON K0A 1A0'
  mapLink: 'https://goo.gl/maps/2viaCeAw5n32'
  tel: '+16132565225'
  telDisplay: (613) 256-5225
