backend:
  name: github
  repo: arobillard/the-hub-almonte

media_folder: "images/uploads"
display_url: https://your-site.com

collections:
  - name: "contact-information"
    label: "Contact Information"
    files:
      - label: "Contact Information"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Telephone Number Data (No spaces or dashes)"
            name: "tel"
            widget: "string"
          - label: "Telephone Number Display"
            name: "telDisplay"
            widget: "string"
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "The Hub Contact Info"
            name: "hubContact"
            widget: "object"
            fields:
            - label: "Telephone Number Data (No spaces or dashes)"
              name: "tel"
              widget: "string"
            - label: "Telephone Number Display"
              name: "telDisplay"
              widget: "string"
            - label: "Address Line 1"
              name: "addressLine1"
              widget: "string"
            - label: "Address Line 2"
              name: "addressLine2"
              widget: "string"
            - label: "Map Link"
              name: "mapLink"
              widget: "string"
          - label: "Rebound Contact Info"
            name: "reboundContact"
            widget: "object"
            fields:
            - label: "Telephone Number Data (No spaces or dashes)"
              name: "tel"
              widget: "string"
            - label: "Telephone Number Display"
              name: "telDisplay"
              widget: "string"
            - label: "Address Line 1"
              name: "addressLine1"
              widget: "string"
            - label: "Address Line 2"
              name: "addressLine2"
              widget: "string"
            - label: "Map Link"
              name: "mapLink"
              widget: "string"
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: _data/pages/home.yml
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"
          - label: "Include Banner?"
            name: "hero"
            widget: "boolean"
            hint: "Turn on to include banner at top of the page."
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Banner Title"
                name: "h1Text"
                widget: "string"
              - label: "Banner Subtitle"
                name: "bylineText"
                widget: "string"
              - label: "Banner Button"
                name: "bannerButton"
                widget: "object"
                fields:
                  - label: "Include button in banner?"
                    name: "heroBtn"
                    widget: "boolean"
                    hint: "Turn on to include button in banner."
                  - label: "Button Link"
                    name: "heroBtnLink"
                    widget: "string"
                  - label: "Button Text"
                    name: "heroBtnText"
                    widget: "string"
              - label: "Banner Image"
                name: "heroImg"
                widget: "image"
          - label: "Include sponsor bar?"
            name: "sponsorBar"
            widget: "boolean"
            hint: "Turn on to include list of sponsors at bottom of page above footer."
      - label: "About"
        name: "about"
        file: _data/pages/about.yml
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"
          - label: "Include Banner?"
            name: "hero"
            widget: "boolean"
            hint: "Turn on to include banner at top of the page."
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Banner Title"
                name: "h1Text"
                widget: "string"
              - label: "Banner Subtitle"
                name: "bylineText"
                widget: "string"
              - label: "Banner Button"
                name: "bannerButton"
                widget: "object"
                fields:
                  - label: "Include button in banner?"
                    name: "heroBtn"
                    widget: "boolean"
                    hint: "Turn on to include button in banner."
                  - label: "Button Link"
                    name: "heroBtnLink"
                    widget: "string"
                  - label: "Button Text"
                    name: "heroBtnText"
                    widget: "string"
              - label: "Banner Image"
                name: "heroImg"
                widget: "image"
          - label: "History Slides"
            name: "history-slides"
            file: _data/slide.yml
            widget: "object"
            fields:
              - label: "Edit History Slides"
                name: "edit-history-slides"
                widget: "list"
                fields:
                  - label: "Slide Name"
                    name: "name"
                    widget: "string"
                    hint: "No capitals, replace spaces with a dash (-)."
                  - label: "Reverse position of Image and Text?"
                    name: "reverse"
                    widget: "boolean"
                    hint: "If selected, the image will appear on the left and the text will be on the right."
                  - label: "Slide Text Background Colour"
                    name: "slideBGColor"
                    widget: "select"
                    default: { label: "White", value: "bg-fff" }
                    options:
                          - { label: "White", value: "bg-fff" }
                          - { label: "Brand Turquoise", value: "bg-primary" }
                          - { label: "Brand Dark Grey", value: "bg-secondary" }
                  - label: "Slide Text Content"
                    name: "content"
                    widget: "markdown"
                  - label: "Slide Image"
                    name: "image"
                    widget: "image"
          - label: "Include sponsor bar?"
            name: "sponsorBar"
            widget: "boolean"
            hint: "Turn on to include list of sponsors at bottom of page above footer."
  - label: "History Slides"
    name: "history-slides"
    files:
      - label: "History Slides"
        name: "history-slides"
        file: _data/slide.yml
        fields:
          - label: "Edit History Slides"
            name: "edit-history-slides"
            widget: "list"
            fields:
              - label: "Slide Name"
                name: "name"
                widget: "string"
                hint: "No capitals, replace spaces with a dash (-)."
              - label: "Reverse position of Image and Text?"
                name: "reverse"
                widget: "boolean"
                hint: "If selected, the image will appear on the left and the text will be on the right."
              - label: "Slide Text Content"
                name: "content"
                widget: "markdown"
              - label: "Slide Image"
                name: "image"
                widget: "image"
