backend:
  name: github
  repo: arobillard/the-hub-almonte

media_folder: "images/uploads"

collections:
  - name: "website-settings"
    label: "Website Setings"
    files:
      - label: "Website Settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Telephone Number Data"
            name: "tel"
            widget: "string"
          - label: "Telephone Number Display"
            name: "telDisplay"
            widget: "string"
