backend:
  name: github
  repo: arobillard/the-hub-almonte

media_folder: "images/uploads"

collections:
  - name: "contact-information"
    label: "Contact Information"
    files:
      - label: "Contact Information"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Telephone Number Data (No spaces or dashes)"
            name: "tel"
            widget: "string"
          - label: "Telephone Number Display"
            name: "telDisplay"
            widget: "string"
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "The Hub Address Line 1"
            name: "hubAddressLine1"
            widget: "string"
          - label: "The Hub Address Line 2"
            name: "hubAddressLine2"
            widget: "string"
          - label: "The Hub Map Link"
            name: "hubMapLink"
            widget: "string"
          - label: "Rebound Address Line 1"
            name: "reboundAddressLine1"
            widget: "string"
          - label: "Rebound Address Line 2"
            name: "reboundAddressLine2"
            widget: "string"
          - label: "Rebound Map Link"
            name: "reboundMapLink"
            widget: "string"
