backend:
  name: github
  repo: arobillard/the-hub-almonte

media_folder: "images/uploads"

collections:
  - name: "contact-information"
    label: "Contact Information"
    files:
      - label: "Contact Information"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Telephone Number Data (No spaces or dashes)"
            name: "tel"
            widget: "string"
          - label: "Telephone Number Display"
            name: "telDisplay"
            widget: "string"
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "The Hub Contact Info"
            name: "hubContact"
            widget: "object"
            fields:
            - label: "Telephone Number Data (No spaces or dashes)"
              name: "tel"
              widget: "string"
            - label: "Telephone Number Display"
              name: "telDisplay"
              widget: "string"
            - label: "Address Line 1"
              name: "addressLine1"
              widget: "string"
            - label: "Address Line 2"
              name: "addressLine2"
              widget: "string"
            - label: "Map Link"
              name: "mapLink"
              widget: "string"
          - label: "Rebound Contact Info"
            name: "reboundContact"
            widget: "object"
            fields:
            - label: "Telephone Number Data (No spaces or dashes)"
              name: "tel"
              widget: "string"
            - label: "Telephone Number Display"
              name: "telDisplay"
              widget: "string"
            - label: "Address Line 1"
              name: "addressLine1"
              widget: "string"
            - label: "Address Line 2"
              name: "addressLine2"
              widget: "string"
            - label: "Map Link"
              name: "mapLink"
              widget: "string"
