backend:
  name: github
  repo: arobillard/the-hub-almonte

media_folder: "images/uploads"
display_url: https://your-site.com

collections:
  - name: "contact-information"
    label: "Contact Information"
    files:
      - label: "Contact Information"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Telephone Number Data (No spaces or dashes)"
            name: "tel"
            widget: "string"
          - label: "Telephone Number Display"
            name: "telDisplay"
            widget: "string"
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "The Hub Contact Info"
            name: "hubContact"
            widget: "object"
            fields:
            - label: "Telephone Number Data (No spaces or dashes)"
              name: "tel"
              widget: "string"
            - label: "Telephone Number Display"
              name: "telDisplay"
              widget: "string"
            - label: "Address Line 1"
              name: "addressLine1"
              widget: "string"
            - label: "Address Line 2"
              name: "addressLine2"
              widget: "string"
            - label: "Map Link"
              name: "mapLink"
              widget: "string"
          - label: "Rebound Contact Info"
            name: "reboundContact"
            widget: "object"
            fields:
            - label: "Telephone Number Data (No spaces or dashes)"
              name: "tel"
              widget: "string"
            - label: "Telephone Number Display"
              name: "telDisplay"
              widget: "string"
            - label: "Address Line 1"
              name: "addressLine1"
              widget: "string"
            - label: "Address Line 2"
              name: "addressLine2"
              widget: "string"
            - label: "Map Link"
              name: "mapLink"
              widget: "string"
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: _data/pages/home.yml
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"
          - label: "Page Headline"
            name: "h1Text"
            widget: "string"
          - label: "Page Byline"
            name: "bylineText"
            widget: "string"
          - label: "Include Banner?"
            name: "hero"
            widget: "boolean"
            hint: "Turn on to include banner at top of the page. The banner will include the Page Headline and Page Byline."
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Banner Button"
                name: "bannerButton"
                widget: "object"
                fields:
                  - label: "Include button in banner?"
                    name: "heroBtn"
                    widget: "boolean"
                    hint: "Turn on to include button in banner."
                  - label: "Button Link"
                    name: "heroBtnLink"
                    widget: "string"
                  - label: "Button Text"
                    name: "heroBtnText"
                    widget: "string"
                  - label: "Button Styles"
                    name: "heroBtnStyle"
                    widget: "string"
                    hint: "Change the style of the button. Type in one of the following colour options: 'btn-white' or 'btn-ghost'. If the button links to another location on this page, add 'smooth-scroll' for nice transition. DO NOT add 'smooth-scroll' if linking to a different page on the website or an external page."
                    required: false
              - label: "Banner Image"
                name: "heroImg"
                widget: "image"
          - label: "Announcements"
            name: "announcements"
            hint: "This section is used to highlight a special items for sale or a contest you are currently running."
            widget: "object"
            fields:
              - label: "Turn on Announcements section?"
                name: "activateAnnouncements"
                widget: "boolean"
              - label: "Announcement Message"
                name: "message"
                widget: "markdown"
              - label: "Announcement Button"
                name: "announcementButton"
                widget: "object"
                fields:
                  - label: "Include button in banner?"
                    name: "announcementBtn"
                    widget: "boolean"
                    hint: "Turn on to include button in banner."
                  - label: "Button Link"
                    name: "announcementBtnLink"
                    widget: "string"
                  - label: "Button Text"
                    name: "announcementBtnText"
                    widget: "string"
                  - label: "Button Styles"
                    name: "announcementBtnStyle"
                    widget: "string"
                    hint: "Change the style of the button. Type in one of the following colour options: 'btn-white' or 'btn-ghost'. If the button links to another location on this page, add 'smooth-scroll' for nice transition. DO NOT add 'smooth-scroll' if linking to a different page on the website or an external page."
                    required: false
              - label: "Announcement Image"
                name: "announcementImg"
                widget: "image"
          - label: "Include sponsor bar?"
            name: "sponsorBar"
            widget: "boolean"
            hint: "Turn on to include list of sponsors at bottom of page above footer."
      - label: "About"
        name: "about"
        file: _data/pages/about.yml
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"
          - label: "Page Headline"
            name: "h1Text"
            widget: "string"
          - label: "Page Byline"
            name: "bylineText"
            widget: "string"
          - label: "Include Banner?"
            name: "hero"
            widget: "boolean"
            hint: "Turn on to include banner at top of the page. The banner will include the Page Headline and Page Byline."
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Banner Button"
                name: "bannerButton"
                widget: "object"
                fields:
                  - label: "Include button in banner?"
                    name: "heroBtn"
                    widget: "boolean"
                    hint: "Turn on to include button in banner."
                  - label: "Button Link"
                    name: "heroBtnLink"
                    widget: "string"
                  - label: "Button Text"
                    name: "heroBtnText"
                    widget: "string"
                  - label: "Button Styles"
                    name: "heroBtnStyle"
                    widget: "string"
                    hint: "Change the style of the button. Type in one of the following colour options: 'btn-white' or 'btn-ghost'. If the button links to another location on this page, add 'smooth-scroll' for nice transition. DO NOT add 'smooth-scroll' if linking to a different page on the website or an external page."
                    required: false
              - label: "Banner Image"
                name: "heroImg"
                widget: "image"
          - label: "History Slides"
            name: "history-slides"
            widget: "object"
            fields:
              - label: "Edit History Slides"
                name: "edit-history-slides"
                widget: "list"
                fields:
                  - label: "Slide Name"
                    name: "name"
                    widget: "string"
                    hint: "No capitals, replace spaces with a dash (-). Ex: the-hub"
                  - label: "Reverse position of Image and Text?"
                    name: "reverse"
                    widget: "boolean"
                    hint: "If selected, the image will appear on the left and the text will be on the right."
                  - label: "Slide Text Background Colour"
                    name: "slideBGColor"
                    widget: "select"
                    default: { label: "White", value: "bg-fff" }
                    options:
                          - { label: "White", value: "bg-fff" }
                          - { label: "Brand Turquoise", value: "bg-primary" }
                          - { label: "Brand Dark Grey", value: "bg-secondary" }
                  - label: "Slide Text Content"
                    name: "content"
                    widget: "markdown"
                  - label: "Slide Image"
                    name: "image"
                    widget: "image"
          - label: "Our Services"
            name: "our-services"
            widget: "list"
            fields:
              - label: "Service Name"
                name: "title"
                widget: "string"
              - label: "Logo"
                name: "logo"
                widget: "image"
              - label: "Service Link"
                name: "link"
                widget: "string"
                hint: "Used to connect the preview list to the full service descripion. Must be in lower case with dashes (-) instead of spaces. Ex: the-hub"
              - label: "Short Description"
                name: "shortDesc"
                widget: "string"
                hint: "Used in preview list of all services."
              - label: "Reverse position of Slide Image and Text?"
                name: "reverse"
                widget: "boolean"
                hint: "If selected, in the services slide the image will appear on the left and the text will be on the right."
              - label: "Long Description"
                name: "longDesc"
                widget: "markdown"
                hint: "Used in slides giving details about the service."
              - label: "Service Slide Image"
                name: "bgImg"
                widget: "image"
          - label: "What We Give?"
            name: "what-we-give"
            widget: "object"
            fields:
              - label: "Banner Title"
                name: "bannerTitle"
                widget: "string"
              - label: "Banner Text"
                name: "bannerText"
                widget: "string"
              - label: "Banner Image"
                name: "bannerImg"
                widget: "image"
              - label: "Donations Title"
                name: "donationsTitle"
                widget: "string"
              - label: "Donations List"
                name: "donations"
                widget: "list"
                fields:
                  - label: "Donor"
                    name: "donor"
                  - label: "Amount"
                    name: "amount"
                    widget: "string"
          - label: "Include sponsor bar?"
            name: "sponsorBar"
            widget: "boolean"
            hint: "Turn on to include list of sponsors at bottom of page above footer."
      - label: "Volunteer"
        name: "volunteer"
        file: _data/pages/volunteer.yml
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"
          - label: "Page Headline"
            name: "h1Text"
            widget: "string"
          - label: "Page Byline"
            name: "bylineText"
            widget: "string"
          - label: "Include Banner?"
            name: "hero"
            widget: "boolean"
            hint: "Turn on to include banner at top of the page. The banner will include the Page Headline and Page Byline."
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Banner Button"
                name: "bannerButton"
                widget: "object"
                fields:
                  - label: "Include button in banner?"
                    name: "heroBtn"
                    widget: "boolean"
                    hint: "Turn on to include button in banner."
                  - label: "Button Link"
                    name: "heroBtnLink"
                    widget: "string"
                  - label: "Button Text"
                    name: "heroBtnText"
                    widget: "string"
                  - label: "Button Styles"
                    name: "heroBtnStyle"
                    widget: "string"
                    hint: "Change the style of the button. Type in one of the following colour options: 'btn-white' or 'btn-ghost'. If the button links to another location on this page, add 'smooth-scroll' for nice transition. DO NOT add 'smooth-scroll' if linking to a different page on the website or an external page."
                    required: false
              - label: "Banner Image"
                name: "heroImg"
                widget: "image"
          - label: "Include sponsor bar?"
            name: "sponsorBar"
            widget: "boolean"
            hint: "Turn on to include list of sponsors at bottom of page above footer."
      - label: "News & Events"
        name: "news-events"
        file: _data/pages/news-events.yml
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"
          - label: "Page Headline"
            name: "h1Text"
            widget: "string"
          - label: "Page Byline"
            name: "bylineText"
            widget: "string"
          - label: "Include Banner?"
            name: "hero"
            widget: "boolean"
            hint: "Turn on to include banner at top of the page. The banner will include the Page Headline and Page Byline."
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Banner Button"
                name: "bannerButton"
                widget: "object"
                fields:
                  - label: "Include button in banner?"
                    name: "heroBtn"
                    widget: "boolean"
                    hint: "Turn on to include button in banner."
                  - label: "Button Link"
                    name: "heroBtnLink"
                    widget: "string"
                  - label: "Button Text"
                    name: "heroBtnText"
                    widget: "string"
                  - label: "Button Styles"
                    name: "heroBtnStyle"
                    widget: "string"
                    hint: "Change the style of the button. Type in one of the following colour options: 'btn-white' or 'btn-ghost'. If the button links to another location on this page, add 'smooth-scroll' for nice transition. DO NOT add 'smooth-scroll' if linking to a different page on the website or an external page."
                    required: false
              - label: "Banner Image"
                name: "heroImg"
                widget: "image"
          - label: "Include sponsor bar?"
            name: "sponsorBar"
            widget: "boolean"
            hint: "Turn on to include list of sponsors at bottom of page above footer."
      - label: "Donate"
        name: "donate"
        file: _data/pages/donate.yml
        fields:
          - label: "Page Title"
            name: "title"
            widget: "string"
          - label: "Page Headline"
            name: "h1Text"
            widget: "string"
          - label: "Page Byline"
            name: "bylineText"
            widget: "string"
          - label: "Include Banner?"
            name: "hero"
            widget: "boolean"
            hint: "Turn on to include banner at top of the page. The banner will include the Page Headline and Page Byline."
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Banner Button"
                name: "bannerButton"
                widget: "object"
                fields:
                  - label: "Include button in banner?"
                    name: "heroBtn"
                    widget: "boolean"
                    hint: "Turn on to include button in banner."
                  - label: "Button Link"
                    name: "heroBtnLink"
                    widget: "string"
                  - label: "Button Text"
                    name: "heroBtnText"
                    widget: "string"
                  - label: "Button Styles"
                    name: "heroBtnStyle"
                    widget: "string"
                    hint: "Change the style of the button. Type in one of the following colour options: 'btn-white' or 'btn-ghost'. If the button links to another location on this page, add 'smooth-scroll' for nice transition. DO NOT add 'smooth-scroll' if linking to a different page on the website or an external page."
                    required: false
              - label: "Banner Image"
                name: "heroImg"
                widget: "image"
          - label: "Include sponsor bar?"
            name: "sponsorBar"
            widget: "boolean"
            hint: "Turn on to include list of sponsors at bottom of page above footer."
